// Generated by tools/narrate.py --index. Track list and section markers for index.html.
window.TRACKS = [
 {
  "file": "01-what-is-epistemology.mp3",
  "text": "../01-what-is-epistemology.md",
  "title": "Chapter 1 — What Is Epistemology?",
  "duration": 2314.7,
  "sections": [
   {
    "title": "Chapter one. What Is Epistemology?",
    "start": 0.0
   },
   {
    "title": "Why epistemology matters for critical thinking",
    "start": 158.9
   },
   {
    "title": "The central questions",
    "start": 334.6
   },
   {
    "title": "Three kinds of knowing",
    "start": 476.0
   },
   {
    "title": "Belief, credence, and acceptance",
    "start": 801.6
   },
   {
    "title": "The basic vocabulary",
    "start": 992.8
   },
   {
    "title": "Three great distinctions",
    "start": 1199.7
   },
   {
    "title": "Epistemic reasons versus practical reasons",
    "start": 1514.6
   },
   {
    "title": "Epistemology is normative",
    "start": 1639.1
   },
   {
    "title": "The map of the field",
    "start": 1795.7
   },
   {
    "title": "How the pieces connect: one news story, twelve questions",
    "start": 1879.0
   },
   {
    "title": "Quick review",
    "start": 1982.5
   },
   {
    "title": "End of chapter one",
    "start": 2276.2
   }
  ]
 },
 {
  "file": "02-history-of-epistemology.mp3",
  "text": "../02-history-of-epistemology.md",
  "title": "Chapter 2 — A History of the Theory of Knowledge",
  "duration": 4646.9,
  "sections": [
   {
    "title": "Chapter two. A History of the Theory of Knowledge.",
    "start": 0.0
   },
   {
    "title": "Ancient Greece",
    "start": 124.9
   },
   {
    "title": "Epistemology in India",
    "start": 956.4
   },
   {
    "title": "Epistemology in the Islamic world",
    "start": 1244.9
   },
   {
    "title": "Epistemology in China",
    "start": 1441.4
   },
   {
    "title": "Medieval and Renaissance Europe",
    "start": 1571.1
   },
   {
    "title": "The early modern revolution",
    "start": 1743.8
   },
   {
    "title": "The nineteenth century",
    "start": 2851.4
   },
   {
    "title": "The twentieth century",
    "start": 3178.5
   },
   {
    "title": "Contemporary directions",
    "start": 3806.7
   },
   {
    "title": "Timeline",
    "start": 3915.3
   },
   {
    "title": "Recurring patterns in the history",
    "start": 4199.6
   },
   {
    "title": "Quick review",
    "start": 4302.7
   },
   {
    "title": "End of chapter two",
    "start": 4625.4
   }
  ]
 },
 {
  "file": "03-logic-and-arguments.mp3",
  "text": "../03-logic-and-arguments.md",
  "title": "Chapter 3 — Logic and the Anatomy of Arguments",
  "duration": 3333.2,
  "sections": [
   {
    "title": "Chapter three. Logic and the Anatomy of Arguments.",
    "start": 0.0
   },
   {
    "title": "What an argument is and is not",
    "start": 109.0
   },
   {
    "title": "Standard form",
    "start": 248.1
   },
   {
    "title": "Deduction, induction, and abduction",
    "start": 360.6
   },
   {
    "title": "Validity and soundness",
    "start": 619.3
   },
   {
    "title": "Strength and cogency",
    "start": 823.3
   },
   {
    "title": "Propositional logic",
    "start": 960.4
   },
   {
    "title": "Valid argument forms",
    "start": 1430.4
   },
   {
    "title": "Formal fallacies",
    "start": 1639.4
   },
   {
    "title": "Categorical logic and syllogisms",
    "start": 1806.9
   },
   {
    "title": "Predicate logic and quantifiers",
    "start": 1960.6
   },
   {
    "title": "Modal logic basics",
    "start": 2093.1
   },
   {
    "title": "Paradoxes as stress tests",
    "start": 2213.1
   },
   {
    "title": "Reconstructing real arguments",
    "start": 2332.1
   },
   {
    "title": "The Toulmin model",
    "start": 2684.2
   },
   {
    "title": "Dialectical moves",
    "start": 2813.7
   },
   {
    "title": "Quick review",
    "start": 2945.2
   },
   {
    "title": "End of chapter three",
    "start": 3313.1
   }
  ]
 },
 {
  "file": "04-language-concepts-and-definitions.mp3",
  "text": "../04-language-concepts-and-definitions.md",
  "title": "Chapter 4 — Language, Concepts, and Definitions",
  "duration": 3023.0,
  "sections": [
   {
    "title": "Chapter four. Language, Concepts, and Definitions.",
    "start": 0.0
   },
   {
    "title": "Why language is an epistemic issue",
    "start": 126.1
   },
   {
    "title": "Use and mention",
    "start": 195.0
   },
   {
    "title": "Sense and reference",
    "start": 252.9
   },
   {
    "title": "Kinds of definition",
    "start": 422.3
   },
   {
    "title": "Rules for good definitions",
    "start": 643.9
   },
   {
    "title": "Necessary and sufficient conditions and their limits",
    "start": 734.2
   },
   {
    "title": "Family resemblance and prototypes",
    "start": 827.9
   },
   {
    "title": "Ambiguity",
    "start": 958.9
   },
   {
    "title": "Vagueness and the sorites paradox",
    "start": 1255.8
   },
   {
    "title": "Verbal disputes",
    "start": 1455.9
   },
   {
    "title": "Loaded language, euphemism, and framing",
    "start": 1632.9
   },
   {
    "title": "Essentially contested concepts",
    "start": 1760.1
   },
   {
    "title": "Thick and thin concepts",
    "start": 1868.0
   },
   {
    "title": "Facts, values, and the is-ought gap",
    "start": 1941.7
   },
   {
    "title": "Thought experiments and intuitions",
    "start": 2109.7
   },
   {
    "title": "Reflective equilibrium",
    "start": 2466.3
   },
   {
    "title": "Conceptual engineering",
    "start": 2565.9
   },
   {
    "title": "Quick review",
    "start": 2665.0
   },
   {
    "title": "End of chapter four",
    "start": 3002.3
   }
  ]
 },
 {
  "file": "05-the-nature-of-knowledge.mp3",
  "text": "../05-the-nature-of-knowledge.md",
  "title": "Chapter 5 — What Is Knowledge?",
  "duration": 3749.3,
  "sections": [
   {
    "title": "Chapter five. What Is Knowledge?",
    "start": 0.0
   },
   {
    "title": "The tripartite analysis",
    "start": 138.8
   },
   {
    "title": "The Gettier problem",
    "start": 398.3
   },
   {
    "title": "Responses to Gettier",
    "start": 869.5
   },
   {
    "title": "The inescapability of Gettier problems",
    "start": 2113.3
   },
   {
    "title": "Epistemic luck",
    "start": 2208.9
   },
   {
    "title": "The value of knowledge",
    "start": 2311.1
   },
   {
    "title": "Understanding and wisdom",
    "start": 2484.8
   },
   {
    "title": "Knowledge-how revisited",
    "start": 2668.3
   },
   {
    "title": "Knowledge, assertion, and action",
    "start": 2778.0
   },
   {
    "title": "Knowing that you know",
    "start": 2920.4
   },
   {
    "title": "Why do we have the concept of knowledge?",
    "start": 3039.3
   },
   {
    "title": "Summary of theories",
    "start": 3176.3
   },
   {
    "title": "Quick review",
    "start": 3353.5
   },
   {
    "title": "End of chapter five",
    "start": 3725.7
   }
  ]
 },
 {
  "file": "06-justification.mp3",
  "text": "../06-justification.md",
  "title": "Chapter 6 — Justification: The Structure of Good Reasons",
  "duration": 3467.6,
  "sections": [
   {
    "title": "Chapter six. Justification: The Structure of Good Reasons.",
    "start": 0.0
   },
   {
    "title": "What justification is",
    "start": 131.7
   },
   {
    "title": "Defeaters",
    "start": 378.2
   },
   {
    "title": "The regress problem",
    "start": 539.3
   },
   {
    "title": "Agrippa's trilemma",
    "start": 611.2
   },
   {
    "title": "Foundationalism",
    "start": 728.3
   },
   {
    "title": "Coherentism",
    "start": 1012.3
   },
   {
    "title": "Infinitism",
    "start": 1284.8
   },
   {
    "title": "Foundherentism",
    "start": 1382.7
   },
   {
    "title": "Critical rationalism",
    "start": 1453.5
   },
   {
    "title": "Comparing the structures",
    "start": 1553.2
   },
   {
    "title": "Internalism and externalism",
    "start": 1651.5
   },
   {
    "title": "Evidentialism",
    "start": 2277.9
   },
   {
    "title": "Reliabilism about justification",
    "start": 2408.3
   },
   {
    "title": "Phenomenal conservatism",
    "start": 2501.9
   },
   {
    "title": "The problem of the criterion",
    "start": 2647.5
   },
   {
    "title": "Deontology and doxastic voluntarism",
    "start": 2765.3
   },
   {
    "title": "Fallibilism",
    "start": 2920.6
   },
   {
    "title": "Quick review",
    "start": 3103.1
   },
   {
    "title": "End of chapter six",
    "start": 3448.1
   }
  ]
 },
 {
  "file": "07-sources-of-knowledge.mp3",
  "text": "../07-sources-of-knowledge.md",
  "title": "Chapter 7 — The Sources of Knowledge",
  "duration": 3376.1,
  "sections": [
   {
    "title": "Chapter seven. The Sources of Knowledge.",
    "start": 0.0
   },
   {
    "title": "Basic and derived sources",
    "start": 114.3
   },
   {
    "title": "Perception",
    "start": 230.4
   },
   {
    "title": "Memory",
    "start": 975.9
   },
   {
    "title": "Introspection and self-knowledge",
    "start": 1234.3
   },
   {
    "title": "Reason and the a priori",
    "start": 1453.5
   },
   {
    "title": "Testimony",
    "start": 1786.6
   },
   {
    "title": "Inference",
    "start": 2619.1
   },
   {
    "title": "Knowledge by presence",
    "start": 2689.4
   },
   {
    "title": "Intuition, emotion, and other candidate sources",
    "start": 2855.2
   },
   {
    "title": "Quick review",
    "start": 3018.8
   },
   {
    "title": "End of chapter seven",
    "start": 3356.1
   }
  ]
 },
 {
  "file": "08-skepticism.mp3",
  "text": "../08-skepticism.md",
  "title": "Chapter 8 — Skepticism and Its Answers",
  "duration": 3480.6,
  "sections": [
   {
    "title": "Chapter eight. Skepticism and Its Answers.",
    "start": 0.0
   },
   {
    "title": "Why study skepticism?",
    "start": 131.0
   },
   {
    "title": "Varieties of skepticism",
    "start": 185.4
   },
   {
    "title": "Pyrrhonian skepticism",
    "start": 298.8
   },
   {
    "title": "Cartesian skepticism",
    "start": 580.2
   },
   {
    "title": "The brain in a vat",
    "start": 679.4
   },
   {
    "title": "The closure argument",
    "start": 759.5
   },
   {
    "title": "Responses to skepticism",
    "start": 897.8
   },
   {
    "title": "Skepticism about induction, other minds, and the past",
    "start": 2504.7
   },
   {
    "title": "The simulation argument",
    "start": 2684.6
   },
   {
    "title": "Healthy and corrosive skepticism",
    "start": 2782.0
   },
   {
    "title": "Quick review",
    "start": 3086.4
   },
   {
    "title": "End of chapter eight",
    "start": 3460.4
   }
  ]
 },
 {
  "file": "09-induction-probability-bayes.mp3",
  "text": "../09-induction-probability-bayes.md",
  "title": "Chapter 9 — Induction, Probability, and Bayesian Reasoning",
  "duration": 4227.1,
  "sections": [
   {
    "title": "Chapter nine. Induction, Probability, and Bayesian Reasoning.",
    "start": 0.0
   },
   {
    "title": "Kinds of non-deductive inference",
    "start": 134.1
   },
   {
    "title": "Hume's problem of induction",
    "start": 245.1
   },
   {
    "title": "Responses to Hume",
    "start": 346.3
   },
   {
    "title": "Goodman's new riddle of induction",
    "start": 641.8
   },
   {
    "title": "The paradox of the ravens",
    "start": 834.2
   },
   {
    "title": "Probability: the basics",
    "start": 995.0
   },
   {
    "title": "Bayes' theorem",
    "start": 1322.3
   },
   {
    "title": "Bayesian epistemology",
    "start": 1918.4
   },
   {
    "title": "Full belief and degrees of belief",
    "start": 2259.7
   },
   {
    "title": "Common errors in probabilistic reasoning",
    "start": 2403.1
   },
   {
    "title": "Calibration and scoring rules",
    "start": 3189.5
   },
   {
    "title": "Statistics and significance",
    "start": 3407.7
   },
   {
    "title": "Quick review",
    "start": 3850.8
   },
   {
    "title": "End of chapter nine",
    "start": 4205.1
   }
  ]
 },
 {
  "file": "10-science-and-evidence.mp3",
  "text": "../10-science-and-evidence.md",
  "title": "Chapter 10 — Science, Evidence, and Explanation",
  "duration": 4194.7,
  "sections": [
   {
    "title": "Chapter ten. Science, Evidence, and Explanation.",
    "start": 0.0
   },
   {
    "title": "What makes science special?",
    "start": 117.5
   },
   {
    "title": "The demarcation problem",
    "start": 227.9
   },
   {
    "title": "Inductivism and its limits",
    "start": 304.7
   },
   {
    "title": "Popper and falsificationism",
    "start": 372.1
   },
   {
    "title": "The Duhem-Quine problem",
    "start": 647.0
   },
   {
    "title": "Ad hoc hypotheses",
    "start": 835.1
   },
   {
    "title": "Kuhn and paradigms",
    "start": 964.0
   },
   {
    "title": "Lakatos and research programmes",
    "start": 1237.0
   },
   {
    "title": "Feyerabend and Laudan",
    "start": 1341.3
   },
   {
    "title": "Inference to the best explanation",
    "start": 1454.8
   },
   {
    "title": "Theory-ladenness of observation",
    "start": 1824.9
   },
   {
    "title": "Underdetermination",
    "start": 1923.9
   },
   {
    "title": "Scientific realism and anti-realism",
    "start": 2029.7
   },
   {
    "title": "Causation and causal inference",
    "start": 2222.6
   },
   {
    "title": "Values in science",
    "start": 3072.6
   },
   {
    "title": "Scientific consensus",
    "start": 3219.9
   },
   {
    "title": "The replication crisis",
    "start": 3394.2
   },
   {
    "title": "Pseudoscience and how to spot it",
    "start": 3612.0
   },
   {
    "title": "Quick review",
    "start": 3827.6
   },
   {
    "title": "End of chapter ten",
    "start": 4175.1
   }
  ]
 },
 {
  "file": "11-truth-and-relativism.mp3",
  "text": "../11-truth-and-relativism.md",
  "title": "Chapter 11 — Truth, Relativism, and Objectivity",
  "duration": 2705.4,
  "sections": [
   {
    "title": "Chapter eleven. Truth, Relativism, and Objectivity.",
    "start": 0.0
   },
   {
    "title": "Why truth matters",
    "start": 141.7
   },
   {
    "title": "Truth-bearers",
    "start": 207.2
   },
   {
    "title": "Theories of truth",
    "start": 273.4
   },
   {
    "title": "The liar paradox",
    "start": 946.8
   },
   {
    "title": "Realism and anti-realism",
    "start": 1103.6
   },
   {
    "title": "Relativism",
    "start": 1170.3
   },
   {
    "title": "Social constructionism",
    "start": 1781.0
   },
   {
    "title": "Perspectivism and objectivity",
    "start": 1970.9
   },
   {
    "title": "Post-truth and bullshit",
    "start": 2134.0
   },
   {
    "title": "Quick review",
    "start": 2362.9
   },
   {
    "title": "End of chapter eleven",
    "start": 2685.3
   }
  ]
 },
 {
  "file": "12-social-epistemology.mp3",
  "text": "../12-social-epistemology.md",
  "title": "Chapter 12 — Social Epistemology: Knowing Together",
  "duration": 3884.8,
  "sections": [
   {
    "title": "Chapter twelve. Social Epistemology: Knowing Together.",
    "start": 0.0
   },
   {
    "title": "Why knowledge is social",
    "start": 125.6
   },
   {
    "title": "Trust and epistemic dependence",
    "start": 232.5
   },
   {
    "title": "Experts and novices",
    "start": 382.2
   },
   {
    "title": "Peer disagreement",
    "start": 772.7
   },
   {
    "title": "Why reasonable people disagree",
    "start": 1235.1
   },
   {
    "title": "Epistemic injustice",
    "start": 1319.9
   },
   {
    "title": "Standpoint and feminist epistemology",
    "start": 1562.9
   },
   {
    "title": "Echo chambers and epistemic bubbles",
    "start": 1772.6
   },
   {
    "title": "Conformity, cascades, and herding",
    "start": 1986.4
   },
   {
    "title": "The wisdom and madness of crowds",
    "start": 2155.3
   },
   {
    "title": "Group knowledge and belief",
    "start": 2388.3
   },
   {
    "title": "Misinformation, disinformation, and propaganda",
    "start": 2535.6
   },
   {
    "title": "Conspiracy theories",
    "start": 2824.5
   },
   {
    "title": "Epistemic institutions",
    "start": 3103.8
   },
   {
    "title": "Epistemic autonomy and artificial intelligence",
    "start": 3303.0
   },
   {
    "title": "Quick review",
    "start": 3519.4
   },
   {
    "title": "End of chapter twelve",
    "start": 3864.4
   }
  ]
 },
 {
  "file": "13-virtues-and-ethics-of-belief.mp3",
  "text": "../13-virtues-and-ethics-of-belief.md",
  "title": "Chapter 13 — Intellectual Virtue and the Ethics of Belief",
  "duration": 3020.6,
  "sections": [
   {
    "title": "Chapter thirteen. Intellectual Virtue and the Ethics of Belief.",
    "start": 0.0
   },
   {
    "title": "The ethics of belief: Clifford and James",
    "start": 120.1
   },
   {
    "title": "Practical reasons for belief",
    "start": 559.2
   },
   {
    "title": "Virtue epistemology",
    "start": 750.2
   },
   {
    "title": "A catalogue of intellectual virtues",
    "start": 932.6
   },
   {
    "title": "Intellectual vices",
    "start": 1247.6
   },
   {
    "title": "Epistemic humility and confidence",
    "start": 1394.3
   },
   {
    "title": "Open-mindedness and its limits",
    "start": 1535.2
   },
   {
    "title": "Pragmatic encroachment",
    "start": 1707.2
   },
   {
    "title": "Moral encroachment",
    "start": 1842.9
   },
   {
    "title": "Faith, reason, and religious epistemology",
    "start": 1971.8
   },
   {
    "title": "Quick review",
    "start": 2693.3
   },
   {
    "title": "End of chapter thirteen",
    "start": 3001.8
   }
  ]
 },
 {
  "file": "14-psychology-of-reasoning.mp3",
  "text": "../14-psychology-of-reasoning.md",
  "title": "Chapter 14 — The Psychology of Reasoning: How Minds Actually Work",
  "duration": 3560.7,
  "sections": [
   {
    "title": "Chapter fourteen. The Psychology of Reasoning: How Minds Actually Work.",
    "start": 0.0
   },
   {
    "title": "Why psychology matters to epistemology",
    "start": 117.4
   },
   {
    "title": "Dual-process theories",
    "start": 222.6
   },
   {
    "title": "Heuristics and biases",
    "start": 402.9
   },
   {
    "title": "Confirmation bias and myside bias",
    "start": 936.8
   },
   {
    "title": "Motivated reasoning",
    "start": 1167.9
   },
   {
    "title": "Belief perseverance and biased assimilation",
    "start": 1326.9
   },
   {
    "title": "Fluency and the illusory truth effect",
    "start": 1434.4
   },
   {
    "title": "Overconfidence and the illusion of explanatory depth",
    "start": 1521.5
   },
   {
    "title": "The Dunning-Kruger effect and its critics",
    "start": 1668.4
   },
   {
    "title": "Identity-protective cognition",
    "start": 1823.7
   },
   {
    "title": "Mindreading: how we attribute knowledge",
    "start": 1999.1
   },
   {
    "title": "The argumentative theory of reasoning",
    "start": 2248.9
   },
   {
    "title": "Ecological rationality",
    "start": 2385.3
   },
   {
    "title": "Replication and the psychology of psychology",
    "start": 2538.2
   },
   {
    "title": "Debiasing: what works",
    "start": 2667.0
   },
   {
    "title": "The scout mindset",
    "start": 2935.9
   },
   {
    "title": "Forecasting and superforecasters",
    "start": 3039.5
   },
   {
    "title": "Quick review",
    "start": 3239.9
   },
   {
    "title": "End of chapter fourteen",
    "start": 3542.6
   }
  ]
 },
 {
  "file": "15-fallacies.mp3",
  "text": "../15-fallacies.md",
  "title": "Chapter 15 — A Field Guide to Fallacies",
  "duration": 3417.6,
  "sections": [
   {
    "title": "Chapter fifteen. A Field Guide to Fallacies.",
    "start": 0.0
   },
   {
    "title": "How to use this field guide",
    "start": 110.8
   },
   {
    "title": "Fallacies of relevance",
    "start": 251.2
   },
   {
    "title": "Fallacies of presumption",
    "start": 1121.0
   },
   {
    "title": "Fallacies of ambiguity",
    "start": 2123.5
   },
   {
    "title": "Causal and statistical fallacies",
    "start": 2405.3
   },
   {
    "title": "Rhetorical tactics that corrupt discussion",
    "start": 2712.8
   },
   {
    "title": "The fallacy fallacy",
    "start": 2889.6
   },
   {
    "title": "Quick reference table",
    "start": 2956.6
   },
   {
    "title": "Practice: spot the fallacy",
    "start": 2971.4
   },
   {
    "title": "End of chapter fifteen",
    "start": 3394.2
   }
  ]
 },
 {
  "file": "16-critical-thinking-toolkit.mp3",
  "text": "../16-critical-thinking-toolkit.md",
  "title": "Chapter 16 — The Critical Thinker's Toolkit: Analyzing Discussions and Framing Arguments",
  "duration": 3657.1,
  "sections": [
   {
    "title": "Chapter sixteen. The Critical Thinker's Toolkit: Analyzing Discussions and Framing Arguments.",
    "start": 0.0
   },
   {
    "title": "The core loop",
    "start": 106.7
   },
   {
    "title": "Step one: Understand before you evaluate",
    "start": 156.9
   },
   {
    "title": "Step two: Identify the kind of disagreement",
    "start": 310.4
   },
   {
    "title": "Stasis theory",
    "start": 461.4
   },
   {
    "title": "Step three: Map the argument",
    "start": 585.2
   },
   {
    "title": "Step four: Evaluate the premises and the reasoning",
    "start": 656.2
   },
   {
    "title": "Step five: Evaluate the evidence",
    "start": 729.6
   },
   {
    "title": "Step six: Find the crux",
    "start": 915.0
   },
   {
    "title": "Step seven: Weigh and conclude",
    "start": 1040.1
   },
   {
    "title": "Framing an argument of your own",
    "start": 1161.9
   },
   {
    "title": "Burden of proof",
    "start": 1470.0
   },
   {
    "title": "Philosophical razors and heuristics",
    "start": 1594.0
   },
   {
    "title": "The baloney detection kit",
    "start": 1835.5
   },
   {
    "title": "The ethics of discussion",
    "start": 1923.8
   },
   {
    "title": "Worked case studies",
    "start": 2220.3
   },
   {
    "title": "Checklists",
    "start": 3387.9
   },
   {
    "title": "Daily practices",
    "start": 3512.8
   },
   {
    "title": "End of chapter sixteen",
    "start": 3624.4
   }
  ]
 }
];
