// Generated by tools/narrate.py --index. Track list and section markers for the Persian player.
window.TRACKS = [
 {
  "file": "01-what-is-epistemology.mp3",
  "text": "../01-what-is-epistemology.md",
  "title": "فصلِ یک: معرفت‌شناسی چیست؟",
  "duration": 2851.2,
  "sections": [
   {
    "title": "فصلِ یک. معرفت‌شناسی چیست؟",
    "start": 0.0
   },
   {
    "title": "چرا معرفت‌شناسی برای تفکرِ نقادانه مهم است",
    "start": 196.8
   },
   {
    "title": "پرسش‌های اصلی",
    "start": 406.9
   },
   {
    "title": "سه گونه دانستن",
    "start": 578.7
   },
   {
    "title": "باور، درجهٔ باور و پذیرش",
    "start": 1003.6
   },
   {
    "title": "واژه‌های پایه",
    "start": 1241.6
   },
   {
    "title": "سه تمایزِ بزرگ",
    "start": 1498.8
   },
   {
    "title": "دلیل‌های معرفتی در برابرِ دلیل‌های عملی",
    "start": 1845.0
   },
   {
    "title": "معرفت‌شناسی هنجاری است",
    "start": 2001.2
   },
   {
    "title": "نقشهٔ این حوزه",
    "start": 2191.7
   },
   {
    "title": "تکه‌ها چطور به هم وصل می‌شوند: یک خبر، دوازده پرسش",
    "start": 2306.8
   },
   {
    "title": "فهمِ خود را بسنجید",
    "start": 2463.3
   },
   {
    "title": "پایانِ فصلِ یک",
    "start": 2810.0
   }
  ]
 }
];
