// Generated by tools/narrate.py --index. Track list and section markers for the Persian player.
window.TRACKS = [
 {
  "file": "01-what-is-epistemology.mp3",
  "text": "../01-what-is-epistemology.md",
  "title": "فصلِ یک: معرفت‌شناسی چیست؟",
  "duration": 2851.2,
  "sections": [
   {
    "title": "فصلِ یک. معرفت‌شناسی چیست؟",
    "start": 0.0
   },
   {
    "title": "چرا معرفت‌شناسی برای تفکرِ نقادانه مهم است",
    "start": 196.8
   },
   {
    "title": "پرسش‌های اصلی",
    "start": 406.9
   },
   {
    "title": "سه گونه دانستن",
    "start": 578.7
   },
   {
    "title": "باور، درجهٔ باور و پذیرش",
    "start": 1003.6
   },
   {
    "title": "واژه‌های پایه",
    "start": 1241.6
   },
   {
    "title": "سه تمایزِ بزرگ",
    "start": 1498.8
   },
   {
    "title": "دلیل‌های معرفتی در برابرِ دلیل‌های عملی",
    "start": 1845.0
   },
   {
    "title": "معرفت‌شناسی هنجاری است",
    "start": 2001.2
   },
   {
    "title": "نقشهٔ این حوزه",
    "start": 2191.7
   },
   {
    "title": "تکه‌ها چطور به هم وصل می‌شوند: یک خبر، دوازده پرسش",
    "start": 2306.8
   },
   {
    "title": "فهمِ خود را بسنجید",
    "start": 2463.3
   },
   {
    "title": "پایانِ فصلِ یک",
    "start": 2810.0
   }
  ]
 },
 {
  "file": "02-history-of-epistemology.mp3",
  "text": "../02-history-of-epistemology.md",
  "title": "فصلِ دو: تاریخِ نظریهٔ معرفت",
  "duration": 5642.2,
  "sections": [
   {
    "title": "فصلِ دو. تاریخِ نظریهٔ معرفت.",
    "start": 0.0
   },
   {
    "title": "یونانِ باستان",
    "start": 148.7
   },
   {
    "title": "معرفت‌شناسی در هند",
    "start": 1188.4
   },
   {
    "title": "معرفت‌شناسی در جهانِ اسلام",
    "start": 1547.1
   },
   {
    "title": "معرفت‌شناسی در چین",
    "start": 1784.5
   },
   {
    "title": "اروپای قرونِ وسطی و رنسانس",
    "start": 1953.5
   },
   {
    "title": "انقلابِ آغازِ دورانِ مدرن",
    "start": 2165.7
   },
   {
    "title": "قرنِ نوزدهم",
    "start": 3488.9
   },
   {
    "title": "قرنِ بیستم",
    "start": 3900.2
   },
   {
    "title": "جهت‌های معاصر",
    "start": 4668.6
   },
   {
    "title": "گاه‌شمار",
    "start": 4800.2
   },
   {
    "title": "الگوهایی که در تاریخ تکرار می‌شوند",
    "start": 5125.9
   },
   {
    "title": "فهمِ خود را بسنجید",
    "start": 5239.7
   },
   {
    "title": "پایانِ فصلِ دو",
    "start": 5617.7
   }
  ]
 }
];
